# Generated by Django 5.2.12 on 2026-03-24 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_veiculo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='acessorios',
            field=models.ManyToManyField(blank=True, null=True, related_name='veiculos', to='core.acessorio'),
        ),
    ]
